apiVersion: apps/v1
kind: Deployment
metadata:
  name: "kubelab"
  labels:
    app: "kubelab"
spec:
  selector:
    matchLabels:
      app: kubelab
  replicas: 1
  template:
    metadata:
      labels:
        app: "kubelab"
    spec:
      containers:
        - name: kubelab
          image: "daimnezes/hello-go:v5.3"

          resources:
            requests:
              cpu: "0.5"
              memory: 20Mi
            limits:
              cpu: "0.5"
              memory: 25Mi

          startupProbe:
            httpGet:
              path: /healthz
              port: 3001
            periodSeconds: 3
            failureThreshold: 30
            initialDelaySeconds: 10
            timeoutSeconds: 1

          readinessProbe:
            httpGet:
              path: /healthz
              port: 3001
            periodSeconds: 3
            failureThreshold: 1
            #initialDelaySeconds: 10

          livenessProbe:
            httpGet:
              path: /healthz
              port: 3001
            periodSeconds: 5
            failureThreshold: 3
            timeoutSeconds: 1
            successThreshold: 1
            initialDelaySeconds: 15

          envFrom:
            - configMapRef:
                name: kubelab-env
            - secretRef:
                name: kubelab-secret
          volumeMounts:
            - mountPath: "/go/myfamily"
              name: config
      volumes:
        - name: config
          configMap:
            name: configmap-family
            items:
            - key: members
              path: "family.txt"