apiVersion: apps/v1
kind: Deployment
metadata:
  name: "kubelab"
  labels:
    app: "kubelab"
spec:
  selector:
    matchLabels:
      app: kubelab
  replicas: 2
  template:
    metadata:
      labels:
        app: "kubelab"
    spec:
      containers:
        - name: kubelab
          image: "daimnezes/hello-go:v5.3"

          startupProbe:
            httpGet:
              path: /healthz
              port: 8000
            periodSeconds: 3
            failureThreshold: 1
            initialDelaySeconds: 30

          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            periodSeconds: 3
            failureThreshold: 1
            #initialDelaySeconds: 10

          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            periodSeconds: 5
            failureThreshold: 3
            timeoutSeconds: 1
            successThreshold: 1
            initialDelaySeconds: 10

          envFrom:
            - configMapRef:
                name: kubelab-env
            - secretRef:
                name: kubelab-secret
          volumeMounts:
            - mountPath: "/go/myfamily"
              name: config
      volumes:
        - name: config
          configMap:
            name: configmap-family
            items:
            - key: members
              path: "family.txt"