apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: kubelab-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    name: kubelab
    kind: Deployment
  minReplicas: 2
  maxReplicas: 30
  targetCPUUtilizationPercentage: 25